name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run clippy (RPi crates only)
        run: cargo clippy -p robot-core -p drivers -p platform_rpi --all-targets -- -D warnings

      - name: Run tests (RPi crates only)
        run: cargo test -p robot-core -p drivers -p platform_rpi --verbose

  cross-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build for aarch64 (RPi-only crates)
        run: |
          cross build --target aarch64-unknown-linux-gnu \
            -p robot-core \
            -p drivers \
            -p platform_rpi
