name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      # 建議在 workspace 根目錄加入 default-members 避開 sim2d
      # default-members = ["r2_core","drivers","platform_rpi"]
      - name: Run clippy (workspace)
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Run tests (workspace)
        run: cargo test --workspace --verbose

  cross-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build for aarch64 (RPi-only crates)
        run: |
          cross build --target aarch64-unknown-linux-gnu \
            -p robot-core \
            -p drivers \
            -p platform_rpi
